version: "3.8"
services:
  web:
    build: .
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    env_file: .env
    ports:
      - 5000:5000
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file: .env
volumes:
  postgres_data: