version: "3.8"
services:
  web:
    container_name: flask_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db
    env_file: .env
    environment:
      - FLASK_ENV=prod
    ports:
      - 5050:5050
    entrypoint:
      - /code/scripts/docker_script.sh
  db:
    container_name: postgres
    image: postgres:13.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file: .env
volumes:
  postgres_data:
