# This Dockerfile is only used to create the image that Jenkins will use.
# It installs Terraform in addition to the standard Dockerfile.

FROM python:3.9.6-slim-buster
LABEL maintainer "Fiifi Krampah"

# Specify Terraform version
ARG TERRAFORM_VERSION="1.2.1"
ARG DEBIAN_FRONTEND=noninteractive

# Add metadata
LABEL terraform_version=${TERRAFORM_VERSION}

# Specify some environment variables
ENV TERRAFORM_VERSION=${TERRAFORM_VERSION}
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV FLASK_ENV=prod

# Update and install the required packages
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get install -y curl libffi-dev unzip openssh-client openssh-server git\
    && curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip '*.zip' -d /usr/local/bin \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm *.zip \
    && apt-get clean \
    && python -m pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY requirements.txt requirements-dev.txt /tmp/

RUN pip install -r /tmp/requirements.txt
RUN pip install -r /tmp/requirements-dev.txt

WORKDIR /code
EXPOSE 5050